# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.55"

  on_macos do
    on_intel do
      sha256 "a0d555b8d1af13bbe20511ce20d4f82d1c8f8ddbf9fd6a17adfc9c37cc70a257"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2b5c53f4dbf80cae81e816edf192b2dfdf01fda499b68b63901ede474871c7f"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c17da428a2ee2684f31d105e6a2cf757c5071f53fffa224a58c6e603eb5bd85"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a604846e589efc2659ab4a790ff018e38f819040f28cd2fd21f7abde7110e4f3"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets manager"
  homepage "https://github.com/br4zz4/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
