# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.70"

  on_macos do
    on_intel do
      sha256 "208a9d300c5131382bde88e38e4a2fc177f7423e0a57b94a77af9b1616f07744"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "32db2e4288d222bc4f3d9b502575c2468b4011c482617468392662c543a938cf"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df699d0716fc32429b621493633c10fe13905b727ae1bce5590c1b9177ddf035"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "efab637339c4cfbc51bf73dbb414cf353edc83a63aba28bbb97a38f617c0f743"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets manager"
  homepage "https://github.com/br4zz4/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
