# This file was generated by GoReleaser. DO NOT EDIT.
cask "ward" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path.to_s]
  end

  version "0.1.74"

  on_macos do
    on_intel do
      sha256 "cb08cd0c3802011b60b32cafee1044d308b0ec0bf3e7feca15a68fea5541f142"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbe5867f12415d182d1b146d6b4287a0b330f3a9b5822c36de1510ebda00df9f"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9933ad463b21391391ae25f2852d91dd15f1f28f99fb7fa0f1f2c1794632be2f"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77392990741daeda43e22ed0dcfa6053288ec11c2b03daec774bdcf2650edd9e"
      url "https://github.com/br4zz4/ward/releases/download/v#{version}/ward_linux_arm64.tar.gz"
    end
  end

  name "ward"
  desc "Hierarchical secrets manager"
  homepage "https://github.com/br4zz4/ward"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ward"
  bash_completion "completions/ward.bash"
  fish_completion "completions/ward.fish"
  zsh_completion "completions/ward.zsh"

  # No zap stanza required

end
